f = open("prasad.txt")
# print(f.tell())
print(f.readline())
# print(f.tell())
print(f.readline())
f.seek(11)
# print(f.tell())
print(f.readline())
# print(f.tell())
print(f.readline())
# print(f.tell())

f.close()