str1 = "This is a Python Program"
print(str1[3])
print(str1[0:4])
print(len(str1))
print(str1[0:24])
print(str1[0:7:2])
print(str1[1:])
print(str1[:4])
print(str1[:])
print(str1[::])
print(str1[::2])
print(str1[::3])
print(str1[::44])
print(str1[-4:-3])
print(str1[::-1])
print(str1[::-2])

print(str1.isalnum())
print(str1.isalpha())
print(str1.endswith("Program"))
print(str1.count("i"))
print(str1.capitalize())
print(str1.lower())
print(str1.upper())
print(str1.find("Python"))
print(str1.replace("Python", "Java"))
print(str1.split(" "))
print(str1.rpartition("Python"))

